# Path to training and validation datasets
path: D:\Python\BTP\SKU110K_fixed  # Root directory of the dataset
train: images/train      # Path to training images (relative to 'path')
val: images/val          # Path to validation images (relative to 'path')
test: images/test        # (Optional) Path to test images (if available)

# Number of classes
nc: 1  # Number of object classes in your dataset

# Class names
names: ["object"]  # List of class names
